In [5]:
!pip install pandas
!pip install numpy

In [6]:
import numpy as np
import pandas as pd

                                         Theortical Questions

Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans>>NumPy is a powerful library in Python designed for numerical computing and data analysis. Its primary purpose is to provide support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.


Key Advantages of NumPy:

1.Performance

2.Memory Efficiency

3.Rich Functionality

4.Interoperability

5.e of Use

Enhancements to Python's Numerical Capabilities:

N-dimensional Arrays (ndarray):

The core data structure in NumPy is the ndarray, which allows for the creation and manipulation of multi-dimensional arrays. This capability is essential for handling large datasets in scientific computing.

Vectorization and Broadcasting:

NumPy supports vectorized operations, which eliminate the need for explicit loops, making the code cleaner and faster. Broadcasting allows for operations between arrays of different shapes, enabling flexible computations.

Universal Functions (ufuncs):

NumPy includes a set of universal functions that operate element-wise on arrays, providing a wide range of mathematical operations that can be applied efficiently.

Advanced Indexing and Slicing:

NumPy allows for sophisticated indexing and slicing techniques, enabling users to access and manipulate subsets of data easily.

Q2>>. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

np.mean()>>

Purpose:
Computes the arithmetic mean (average) of the elements in an array.

In [10]:
a=[1,2,3,4,5,6,7,8]
np.mean(a)

np.float64(4.5)

np.average()

Purpose:
Computes the weighted average of the elements in an array. If no weights are provided, it behaves like np.mean().

In [12]:
np.average(a)

np.float64(4.5)

Q3>>. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Reversing a 1D Array>>

For a 1D array, you can reverse the array using slicing. The syntax for reversing is array[::-1], which means "take all elements in reverse order."

In [13]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the 1D array
reversed_arr_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_arr_1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


Reversing a 2D Array>>

For a 2D array, you can reverse the array along different axes using slicing. You can specify the axis along which to reverse the array.

In [14]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along the first axis (rows)
reversed_rows = arr_2d[::-1, :]
print("Reversed along the first axis (rows):")
print(reversed_rows)

# Reverse along the second axis (columns)
reversed_columns = arr_2d[:, ::-1]
print("\nReversed along the second axis (columns):")
print(reversed_columns)

# Reverse along both axes
reversed_both = arr_2d[::-1, ::-1]
print("\nReversed along both axes:")
print(reversed_both)

Reversed along the first axis (rows):
[[7 8 9]
 [4 5 6]
 [1 2 3]]

Reversed along the second axis (columns):
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Reversed along both axes:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


Q4>>4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In NumPy, you can determine the data type of elements in an array using the .dtype attribute of the NumPy array. This attribute returns a NumPy data type object that describes the type of the elements contained in the array.

In [15]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
data_type = arr.dtype

print("Data type of the array elements:", data_type)

Data type of the array elements: int64


Q5>> Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Key Features of ndarrays
Homogeneous Data Types:

All elements in a NumPy array must be of the same data type (e.g., all integers, all floats). This uniformity allows for optimized memory usage and performance.

Multi-dimensional:

ndarrays can have any number of dimensions (1D, 2D, 3D, etc.). The number of dimensions is referred to as the "rank" of the array. For example, a 1D array is a vector, a 2D array is a matrix, and a 3D array can represent a tensor.

Efficient Memory Layout:

NumPy arrays are stored in contiguous blocks of memory, which allows for efficient access and manipulation of data. This is in contrast to Python lists, which can store elements in non-contiguous memory locations.

Vectorized Operations:

NumPy supports element-wise operations on arrays, allowing for efficient mathematical computations without the need for explicit loops. This feature is known as "vectorization" and leads to more concise and faster code.

Broadcasting:

NumPy arrays support broadcasting, which allows operations between arrays of different shapes. This feature enables automatic expansion of smaller arrays to match the shape of larger arrays during arithmetic operations.



coclusion>>NumPy's ndarrays are a fundamental component of the library, providing a powerful and efficient way to handle numerical data. Their homogeneous nature, support for multi-dimensional arrays, and optimized performance make them superior to standard Python lists for numerical computations. Understanding these differences is crucial for leveraging the full potential of NumPy in scientific computing and data analysis.

Q6>>Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

1. Memory Layout and Contiguous Storage
   
NumPy arrays store elements in contiguous blocks of memory, which allows for efficient access and manipulation of data. In contrast, Python lists store elements in non-contiguous memory locations, leading to slower access times.

2. Vectorized Operations
   
NumPy arrays support vectorized operations, which enable element-wise operations on entire arrays without the need for explicit loops. This leads to significant performance improvements for large-scale numerical operations.


3. Optimized Algorithms and BLAS Integration
   
Performance Benefit: NumPy arrays can perform linear algebra operations up to 10-100 times faster than Python lists due to their optimized algorithms and BLAS integration.

4. Cache Efficiency
   
Performance Benefit: NumPy arrays can reduce cache misses by up to 90% compared to Python lists, leading to significant performance improvements.



In [16]:
import numpy as np
import time

# Create a large Python list and NumPy array
python_list = [i for i in range(1000000)]
numpy_array = np.arange(1000000)

# Measure the time taken for element-wise operations
start_time = time.time()
result_list = [x * 2 for x in python_list]
end_time = time.time()
print("Python list time:", end_time - start_time)

start_time = time.time()
result_array = numpy_array * 2
end_time = time.time()
print("NumPy array time:", end_time - start_time)

Python list time: 0.07716059684753418
NumPy array time: 0.01501154899597168


Q7>>7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

vstack>>

vstack() is used to stack arrays on top of each other, resulting in a new array with increased row dimensionality. This function is useful when you need to combine multiple arrays with the same number of columns.

In [17]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack arrays vertically
stacked_array = np.vstack((array1, array2))

print(stacked_array)

[[1 2 3]
 [4 5 6]]


hstack() >>

hstack() is used to stack arrays side by side, resulting in a new array with increased column dimensionality. This function is useful when you need to combine multiple arrays with the same number of rows.

In [18]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack arrays horizontally
stacked_array = np.hstack((array1, array2))

print(stacked_array)

[1 2 3 4 5 6]


Q8>>Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

fliplr() Method:

The fliplr() method flips an array horizontally, i.e., it reverses the order of elements along the last axis (axis=-1). This method is useful when you need to mirror an array around its vertical axis.

In [19]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Flip the array horizontally
flipped_array = np.fliplr(array)

print(flipped_array)


[[3 2 1]
 [6 5 4]]


flipud() Method:

The flipud() method flips an array vertically, i.e., it reverses the order of elements along the first axis (axis=0). This method is useful when you need to mirror an array around its horizontal axis.

In [20]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Flip the array vertically
flipped_array = np.flipud(array)

print(flipped_array)

[[4 5 6]
 [1 2 3]]


Q9.>> Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into sub-arrays along a specified axis. This method is useful when you need to divide an array into smaller chunks, such as when processing large datasets in parallel.

In [24]:

import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array into 3 sections
sub_arrays = np.array_split(array, 3)

print(sub_arrays)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Q10>>Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Vectorization:

Vectorization is the process of performing operations on entire arrays at once, rather than iterating over individual elements. This is achieved by using NumPy's built-in functions and operators, which are designed to work with arrays.

In [25]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Perform element-wise addition using vectorization
result = array1 + array2

print(result)

[ 7  9 11 13 15]


Broadcasting:

Broadcasting is the process of aligning arrays with different shapes and sizes so that they can be operated on element-wise. This is achieved by adding dimensions to the arrays as needed, so that they can be aligned.

In [26]:
import numpy as np

# Create two arrays with different shapes
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6])

# Perform element-wise addition using broadcasting
result = array1 + array2

print(result)

[ 7  8  9 10 11]


Q1>>Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [28]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = np.transpose(array)


print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[44 16 18]
 [39 25 37]
 [74 38  2]]

Transposed Array:
[[44 39 74]
 [16 25 38]
 [18 37  2]]


Q2>>Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [29]:
import numpy as np

# Generate a 1D array with 10 elements
array = np.arange(1, 11)

print("Original 1D Array:")
print(array)

# Reshape the array into a 2x5 array
array_2x5 = array.reshape(2, 5)

print("\nReshaped 2x5 Array:")
print(array_2x5)

# Reshape the array into a 5x2 array
array_5x2 = array.reshape(5, 2)

print("\nReshaped 5x2 Array:")
print(array_5x2)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Q3>>Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [30]:
import numpy as np

# Create a 4x4 array with random float values
array = np.random.rand(4, 4)

print("Original 4x4 Array:")
print(array)

# Add a border of zeros around the array
bordered_array = np.pad(array, 1, mode='constant')

print("\nBordered 6x6 Array:")
print(bordered_array)

Original 4x4 Array:
[[0.01740771 0.84165114 0.172406   0.92906747]
 [0.42371244 0.88042684 0.82036395 0.84400565]
 [0.14627433 0.24587066 0.38085141 0.92008963]
 [0.69441876 0.68322607 0.38204273 0.47747636]]

Bordered 6x6 Array:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.01740771 0.84165114 0.172406   0.92906747 0.        ]
 [0.         0.42371244 0.88042684 0.82036395 0.84400565 0.        ]
 [0.         0.14627433 0.24587066 0.38085141 0.92008963 0.        ]
 [0.         0.69441876 0.68322607 0.38204273 0.47747636 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4>>Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [31]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)

print("Array of Integers from 10 to 60 with a Step of 5:")
print(array)

Array of Integers from 10 to 60 with a Step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


Q5>>Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [32]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

# Print the results
print("Original Array:")
print(array)

print("\nUppercase Array:")
print(uppercase_array)

print("\nLowercase Array:")
print(lowercase_array)

print("\nTitlecase Array:")
print(titlecase_array)

print("\nCapitalized Array:")
print(capitalize_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Titlecase Array:
['Python' 'Numpy' 'Pandas']

Capitalized Array:
['Python' 'Numpy' 'Pandas']


Q6>>Generate a NumPy array of words. Insert a space between each character of every word in the array

In [34]:
import numpy as np

# Generate a NumPy array of words
array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_array = np.array([' '.join(word) for word in array])

print("Original Array:")
print(array)

print("\nArray with Spaces Between Characters:")
print(spaced_array)





Original Array:
['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


Q7>>Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [35]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Perform element-wise addition
addition = array1 + array2
print("\nElement-wise Addition:")
print(addition)

# Perform element-wise subtraction
subtraction = array1 - array2
print("\nElement-wise Subtraction:")
print(subtraction)

# Perform element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication)

# Perform element-wise division
division = array1 / array2
print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q8>>Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [37]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


Q9>>9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.


In [38]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, 100)

print("Random Array:")
print(random_array)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    max_divisor = int(np.sqrt(n)) + 1
    for d in range(3, max_divisor, 2):
        if n % d == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

print("\nPrime Numbers:")
print(prime_numbers)

Random Array:
[321 567 381 234 427  51 647 815 801 125 343 453  55 579 346 545 495 653
 633 464 510 429 648 850 301 167 564 599 610 900 678 544 435 389 569 205
  71 912 927 241 890 702 553 966 521 466 110 800 987 545 202 768 292 604
 898 308 272 187 201 288  80 576 169 272 400 888 545 473 614 915 151 341
 723 306 611 846 435 505 370 971  21 266  85 996 292 146  93 244 417   6
 123 919 962 688 752  56 314 881 176 355]

Prime Numbers:
[np.int32(647), np.int32(653), np.int32(167), np.int32(599), np.int32(389), np.int32(569), np.int32(71), np.int32(241), np.int32(521), np.int32(151), np.int32(971), np.int32(919), np.int32(881)]


Q10>>Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [42]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month
# Let's assume the month has 30 days
daily_temperatures = np.random.uniform(20, 30, 30)

print("Daily Temperatures:")
print(daily_temperatures)

# Calculate the weekly averages
weeks = np.split(daily_temperatures[:28], 4)
weekly_averages = [np.mean(week) for week in weeks]

# Calculate the average of the remaining days
remaining_days_average = np.mean(daily_temperatures[28:])

print("\nWeekly Averages:")
for i, average in enumerate(weekly_averages):
    print(f"Week {i+1}: {average}")

print("\nAverage of the remaining days:")
print(remaining_days_average)

Daily Temperatures:
[20.91359437 26.060264   20.00207801 24.9411434  29.41544843 25.54280985
 22.92359713 26.38710595 24.01734895 22.42258961 26.07238037 26.41331341
 28.59227333 22.4545087  28.59176712 25.93635923 23.83478065 29.66975975
 27.61538159 29.82533803 29.62927277 22.19440941 26.7681055  27.84738705
 28.81912994 29.18603851 21.0024099  28.98423151 26.3963172  23.17657851]

Weekly Averages:
Week 1: 24.256990740749465
Week 2: 25.194217190139945
Week 3: 27.871808449865746
Week 4: 26.400244544035825

Average of the remaining days:
24.78644785417108
